seed: None # Either None or an integer
num_simulations: 10
n_cores: -1 # For multitasking, set to 1 for debugging and single tasking

dgp:
  n_samples: 250
  design: Exponential # Either Exponential, 5, or 50 in Spindler
  mu2: 30
  n_instruments: 100 # Fixed in spindler
  beta_true: 1.0 # Fixed in spindler
  sigma_e: 1.0 # Fixed in spindler
  rho_ev: 0.6 # Fixed in spindler
  sigma_z: 1.0 # Fixed in spindler
  correlation: 0.5 # Fixed in spindler

# split:
#   test_size: 0.2
#   random_state: 42

lasso:
  method: standard_lasso
  kwargs:
    lambda_method: cv
    cv: 10 # Following spindler
    max_iter: 10000 # Arbitrarily picked

regression:
  method: 2sls
  alpha: 0.05
